# Draw a house

from turtle import *

bgcolor('green')

def house():
    begin_fill()
    color('DarkSlateGrey')
    forward(100)
    left(90)
    forward(80)
    left(90)
    forward(100)
    left(90)
    forward(80)
    end_fill()
    
house()

def window(x, y):
    penup()
    goto(x, y)
    setheading(90)
    pendown()
    begin_fill()
    color('DimGray')
    for i in range(4):
        forward(20)
        right(90)
    end_fill()

window(15, 55)
window(65, 55)

def door():
    penup()
    goto(45, 0)
    setheading(90)
    pendown()
    begin_fill()
    color('coral')
    forward(20)
    right(90)
    forward(15)
    right(90)
    forward(20)
    right(90)
    forward(15)
    end_fill()
door()

def roof():
    penup()
    goto(-10, 80)
    setheading(0)
    pendown()
    begin_fill()
    color('burlywood')
    forward(120)
    left(135)
    forward(85)
    left(90)
    forward(85)
    left(135)
    end_fill()
roof()

def porch():
    penup()
    goto(-10, 0)
    setheading(0)
    pendown()
    begin_fill()
    pencolor('green')
    color('burlywood4')
    forward(120)
    right(90)
    forward(20)
    right(90)
    forward(120)
    right(90)
    forward(20)
    # porch steps
    home()
    setheading(0)
    goto(45, 0)
    forward(15)
    right(90)
    forward(10)
    right(90)
    forward(15)
    right(90)
    forward(10)
    right(180)
    forward(20)
    left(90)
    forward(15)
    left(90)
    forward(10)
    left(90)
    forward(15)
    right(90)
    forward(10)
    end_fill()
porch()

mainloop()